### ISSUE TITLE
Please tag version 1.1

### ISSUE THREAD

**Issue by sjackman** [pmelsted/KmerStream#3]
Verision 1.0 doesn't include `added options for doing multiple values of k simultaneously`

**Comment by pmelsted** [comment]
Fixed in  38c20a5

**Comment by sjackman** [comment]
Thanks, Pall! The `README.md` is not included in the tarball.
branch `origin/master` is at 38c20a5e7c8827a2c469410c3b9dac6dcca3fecb
but tag `origin/v1.1` is at 12a66ea37190f0fb8096e9c42e0cf60ed6042190

If you rerelease the tarball, would you consider renaming the executables to have a common prefix:
i.e.
KmerStream, KmerStream-join, KmerStream-estimate
`estimate.py` is quite generic and could conflict with other installed packages.

**Comment by pmelsted** [comment]
Executable names have been fixed, the tarball for v1.1 should be up to date.

**Comment by sjackman** [comment]
Thanks, Pall. Looks great. It'll be merged into Homebrew-Science soon: https://github.com/Homebrew/homebrew-science/pull/3694

**Comment by sjackman** [comment]
Merged!
