### ISSUE TITLE
Output TSV optionally

### ISSUE THREAD

**Issue by sjackman** [pmelsted/KmerStream#6]
Much better for importing into R and Python. e.g.
```tsv
Q	k	F0	f1	F1
0	32	15686875710	12361159570	188878769625
0	64	145132117825	134005267461	161086206625
0	96	120458305249	111221687401	133300308154
0	128	21617343636	18233322390	105522711154
0	160	19369615797	15914061304	77772705236
0	192	46485745358	43797611019	50099054358
0	224	21147873853	20060404949	22586521835
```

**Comment by sjackman** [comment]
It would terribly useful to add additional columns for
F<sub>0</sub>-f<sub>1</sub>, G, e<sub>k</sub>, &lambda;

**Comment by pmelsted** [comment]
Will do. The first line will be prefixed by '#'.

The remaining fields will be computed by a python script and can be added on.

**Comment by sjackman** [comment]
Thanks, Pall! I prefer no `#`. The TSV tools that I use expect a header line.

**Comment by pmelsted** [comment]
Fixed in 38c20a

**Comment by sjackman** [comment]
Just because I had it lying around, here's a script to convert the previous `kmerstream` output format to TSV.
```sh
#!/bin/sh
set -eu -o pipefail
(printf "Q\tk\tF0\tf1\tF1\n"; \
	gsed 's/[^ ]* = //g;s/, /\n/' "$@" | paste -d'\t' - - - - -) \
	| estimate.py /dev/stdin
```
