### ISSUE TITLE
Wacky results for F0-f1

### ISSUE THREAD

**Issue by sjackman** [pmelsted/KmerStream#7]
I ran KmerStream on the Genome in a Bottle 72x PE 2x250 data for HG004. The result for F<sub>0</sub>-f<sub>1</sub> is ~3.4 billion for k=32, k=128 and k=160, which sounds reasonable since it's diploid. For k=64 it's 11 billion and for k=96 it's 9 billion. What's up with that? Any ideas?

|Q    |k    |F0            |f1            |F1            |F0-f1 |
|-----|-----|--------------|--------------|--------------|---------- |
|0    |32   |15686875710   |12361159570   |188878769625  |3325716140 |
|0    |64   |145132117825  |134005267461  |161086206625  |11126850364 |
|0    |96   |120458305249  |111221687401  |133300308154  |9236617848 |
|0    |128  |21617343636   |18233322390   |105522711154  |3384021246 |
|0    |160  |19369615797   |15914061304   |77772705236   |3455554493 |
|0    |192  |46485745358   |43797611019   |50099054358   |2688134339 |
|0    |224  |21147873853   |20060404949   |22586521835   |1087468904 |

**Comment by pmelsted** [comment]
The hash function uses 128 bits of state space using a pair of 64 bit ints. The 64 bit value returned is the low part of the XOR of the hash value for the k-mer and it's reverse complement. For even values of k there are values which are then hashed to 0, I'm guessing that's what's happening here. 

I would suggest using odd values of k, I'm guessing if  you use 63 or 95 it should give similar results to the others.

**Comment by sjackman** [comment]
This affects palindromic k-mers? I'll try odd k. If it is due to palindromic k-mer, perhaps it should be special cased so that when the hash of both the k-mer and its reverse complement are identical, the hash is that value rather than then xor of the two, which is zero.

**Comment by sjackman** [comment]
Here's the results for various values of *k* both even and odd:

Q    |k    |F0            |f1            |F1            |F0-f1          |G              |e                |lambda
---  |---  |---           |---           |---           |---            |---            |---              |---
0    |31   |14983528304   |11574665723   |189747469601  |3408862581.0   |3168801194.51  |0.0635480682714  |59.8798908337
0    |32   |15686875710   |12361159570   |188878769625  |3325716140.0   |3048854388.33  |0.0683982996587  |61.9507347902
0    |63   |21085483259   |17655805565   |161954610765  |3429677694.0   |3157664513.23  |0.112393290944   |51.2893659495
0    |64   |145132117825  |134005267461  |161086206625  |11126850364.0  |27664146708.6  |0.788787382671   |5.82292337884
0    |95   |121202175353  |112227361920  |134168534215  |8974813433.0   |24147085988.8  |0.783330667123   |5.55630332693
0    |96   |120458305249  |111221687401  |133300308154  |9236617848.0   |30551814270.6  |0.758837782096   |4.36308976526
0    |127  |97168929800   |90854466174   |106390518580  |6314463626.0   |16130872763.3  |0.810943126502   |6.59545953535
0    |128  |21617343636   |18233322390   |105522711154  |3384021246.0   |3248084441.44  |0.175373338582   |32.4876748301
0    |159  |19391282222   |15976187164   |78639069147   |3415095058.0   |3333748282.85  |0.205230774053   |23.5887842977
0    |160  |19369615797   |15914061304   |77772705236   |3455554493.0   |3376381205.05  |0.206662105149   |23.0343378051
0    |191  |15843473767   |12529561571   |50961964228   |3313912196.0   |3272008278.75  |0.247514581856   |15.5751330334
0    |192  |46485745358   |43797611019   |50099054358   |2688134339.0   |10694127607.7  |0.801086136241   |4.68472569204
0    |223  |21945322921   |20778183027   |23442687548   |1167139894.0   |6168674174.38  |0.795967742364   |3.8002797498
0    |224  |21147873853   |20060404949   |22586521835   |1087468904.0   |4674196335.27  |0.817386516901   |4.83217225271

**Comment by sjackman** [comment]
The genome size estimates are around 3 Gbp for k = 31 to 63 and 128 to 224, but around 10 Gbp for k = 64 to 127.

k    |F0-f1        |G        |e
---  |---      |---      |---
31   |3.40886  |3.1688   |0.0635480682714
32   |3.32572  |3.04885  |0.0683982996587
63   |3.42968  |3.15766  |0.112393290944
64   |11.1269  |27.6641  |0.788787382671
95   |8.97481  |24.1471  |0.783330667123
96   |9.23662  |30.5518  |0.758837782096
127  |6.31446  |16.1309  |0.810943126502
128  |3.38402  |3.24808  |0.175373338582
159  |3.4151   |3.33375  |0.205230774053
160  |3.45555  |3.37638  |0.206662105149
191  |3.31391  |3.27201  |0.247514581856
192  |2.68813  |10.6941  |0.801086136241
223  |1.16714  |6.16867  |0.795967742364
224  |1.08747  |4.6742   |0.817386516901

**Comment by sjackman** [comment]
I corrected the above reads using BFC and assembled with ABySS, and counted the number of distinct k-mers (F0) exactly using ABySS.

Tool        |k    |F0
---         |---  |---
KmerStream  |31   |6647018127
KmerStream  |32   |6852707847
ABySS       |32   |7175140434
KmerStream  |63   |9107196012
KmerStream  |64   |**142126681475**
ABySS       |64   |9097982371
KmerStream  |95   |**118756558961**
KmerStream  |96   |**117838430724**
ABySS       |96   |9422137746
KmerStream  |127  |94774781346
KmerStream  |128  |9163288034
ABySS       |128  |9063966262
KmerStream  |159  |8366513720
KmerStream  |160  |8322625638
KmerStream  |191  |7121391997
KmerStream  |192  |45128831570
KmerStream  |223  |21194731550
KmerStream  |224  |20411264353

**Comment by sjackman** [comment]
The data is `HG004` from here: https://github.com/genome-in-a-bottle/giab_data_indexes/blob/master/AshkenazimTrio/sequence.index.AJtrio_Illumina_2x250bps_06012016

**Comment by luizirber** [comment]
About palindromic kmers, we had the same issue recently in the HLL implementation in khmer: https://github.com/dib-lab/khmer/issues/1353 and ended up doing exaclty what @sjackman suggested: https://github.com/dib-lab/khmer/pull/1355/files

**Comment by sjackman** [comment]
I want to know whether there are other species of *k*-mers that also produce bad (low-information content) hash values when you xor the hash of the *k*-mer and the hash of its reverse complement. Palindromes are the worst case with zero information content.

**Comment by sjackman** [comment]
Perhaps there are better commutative mixing functions, such as taking the `min` of the two hash values.

**Comment by pmelsted** [comment]
The badness depends on the hash function, as long as there is no structure in it related to reverse complement it shouldn't be an issue

Even `+` is easier and avoids the issue of `xor`. In any case I've started the download.

**Comment by sjackman** [comment]
I'm seeing that
31 ≤ *k* ≤ 63 yields expected results.
64 ≤ *k* ≤ 127 yields unexpected results.
128 ≤ *k* ≤ 191 yields expected results.
192 ≤ *k* ≤ 225 yields unexpected results.

**Comment by sjackman** [comment]
Q    |k    |F0            |f1            |F1            |F0-f1          |G              |e                |lambda
---  |---  |---           |---           |---           |---            |---            |---              |---
0    |31   |6583267269    |3812999219    |189855443726  |2770268050.0   |2741168859.55  |0.0203910154982  |69.2607619063
0    |32   |6833603685    |4070561656    |188986884754  |2763042029.0   |2730767511.96  |0.0218813113653  |69.2065083996
0    |33   |6933594507    |4134265166    |188118333462  |2799329341.0   |2767493220.02  |0.0223162750129  |67.9742707592
0    |63   |9108946311    |6005316346    |162065506159  |3103629965.0   |3072138554.6   |0.0374441746436  |52.7533193178
0    |64   |142381287401  |128846464771  |161197153404  |13534822630.0  |45694952346.0  |0.704174248113   |3.52767964792
0    |65   |141238890517  |128055368047  |160328804779  |13183522470.0  |36550941386.7  |0.728037484059   |4.38644802832
0    |95   |119036750375  |107664504973  |134280222158  |11372245402.0  |48327405721.6  |0.674453281569   |2.77855225525
0    |96   |118010306557  |106938277844  |133412004227  |11072028713.0  |38902523676.3  |0.700146748014   |3.42939201932
0    |97   |117448489335  |106341840420  |132543791832  |11106648915.0  |43850549736.1  |0.685627460151   |3.02262554585
0    |127  |94776863611   |86241329011   |106502002063  |8535534600.0   |32276217378.7  |0.702555065564   |3.29970519201
0    |128  |9200409063    |5933992750    |105634175907  |3266416313.0   |3252228482.99  |0.0564437692433  |32.4805518615
0    |129  |9138756101    |5844839807    |104766373208  |3293916294.0   |3280378176.85  |0.0560479168505  |31.9372851421
0    |159  |8394983190    |5076315917    |78749437854   |3318667273.0   |3310472724.05  |0.0646698440979  |23.7879736274
0    |160  |8313046852    |4974220406    |77883022939   |3338826446.0   |3331056788.53  |0.0640674651797  |23.3808751647
0    |161  |8317101431    |5000384332    |77016678218   |3316717099.0   |3308861736.28  |0.0651300920235  |23.2758828734
0    |191  |7102119285    |3793138650    |51070077798   |3308980635.0   |3305203110.64  |0.074421844871   |15.4514188958
0    |192  |44943131884   |41042336370   |50207082693   |3900795514.0   |16384608793.3  |0.700439312917   |3.06428327502
0    |193  |44192417397   |40379700963   |49344241549   |3812716434.0   |15901746755.3  |0.702792656423   |3.1030705185
0    |223  |21204523750   |19438086524   |23547011882   |1766437226.0   |8151454639.09  |0.701602383599   |2.88868832921
0    |224  |20400302262   |18690401998   |22690708545   |1709900264.0   |7481473586.84  |0.705387731241   |3.0329196891
0    |225  |19638524129   |17921579933   |21834690732   |1716944196.0   |9862068124.19  |0.662336095904   |2.21400729107

**Comment by sjackman** [comment]
![plot-f0-vs-k](https://cloud.githubusercontent.com/assets/291551/15981283/045b26ae-2f28-11e6-9737-1049d09d077c.png)
See http://rpubs.com/sjackman/hg004-kmer-counts

**Comment by pmelsted** [comment]
I've been looking at the code for the hash function and now that I've recalled the nitty gritty details I remember why this happens.

The hash function I implemented is a variant of the one in http://arxiv.org/pdf/0705.4676.pdf 

The differences are that we keep track of the state of the hash function on the forward and reverse strand at the same time, `h` and `ht` in the code and compute the resulting updates as a rolling hash function. The hash states are 128bit integers implemented as a struct of two 64-bit unsigned ints. This means that they could in theory go up to k=127 and I've implemented that functionality.

I can't really vouch for hash values beyond k=127 because you'll get a possible cancellation effects. The only way around this would be to increase the state size up to 256bits or so. However they may work just fine, caveat emptor.

I'll test this on the HG004 dataset soon.

**Comment by sjackman** [comment]
It doesn't seem to work though for 64 ≤ k ≤ 127. Thanks for looking into it, Pall.

**Comment by pmelsted** [comment]
This version should be fixed, 5a8c13e

**Comment by sjackman** [comment]
Thanks, Pall. Do you expect that to also fix 192 ≤ k ≤ 255?

**Comment by pmelsted** [comment]
Yes, those values should behave better. Still running HG004

**Comment by pmelsted** [comment]
Not comparable to the reads you have above because this is uncorrected.


Tool |k |F0
|--- |--- |---
KmerStream |31 |15147106307
KmerStream |32 |15658318903
KmerStream |63 |21067938256
KmerStream |64 |21165276062
KmerStream |95 |22203386480
KmerStream |96 |22214367988
KmerStream |127 |21543694211
KmerStream |128 |21560582654
KmerStream |159 |19380546839
KmerStream |160 |19410237429
KmerStream |191 |15847347308
KmerStream |192 |15775540516
KmerStream |223 |10296089124
KmerStream |224 |10059439133

These seem to give more stable estimates of the genome size and other parameters

F0-f1|G|e|lambda
|---|---|---|---
3314597937.0|3053325878.1|0.0651332567337|62.1445195098
3309618534.0|3031668483.57|0.0683440518093|62.301920757
3482986038.0|3218506192.94|0.111861901649|50.3198070956
3478386113.0|3214803045.68|0.113086417847|50.1076440255
3510735486.0|3321128445.33|0.142158094103|40.3984779341
3568629989.0|3385656011.11|0.142631922723|39.3720767014
3437288047.0|3304532775.98|0.172689864263|32.1953285963
3458667545.0|3327981207.55|0.174028085859|31.7077244651
3483996669.0|3405176340.89|0.204153634889|23.0939784829
3425135552.0|3344476528.46|0.207613861196|23.254074165
3308860931.0|3266823343.61|0.247694849307|15.599853089
3323908173.0|3282990343.25|0.250185024965|15.2601893761
2902175654.0|2973736401.21|0.313495750312|7.8832432957
2862059297.0|2946513598.95|0.316178692423|7.6655074129

**Comment by sjackman** [comment]
Great! Will you tag a new stable release?

**Comment by pmelsted** [comment]
tag v1.1 is latest stable release now

**Comment by sjackman** [comment]
It works! Thanks for the fix, Pall. Here's a new comparison figure. ABySS is using `q=3` and KmerStream `Q=0` (my fault) so that may account for the bias. Do you know whether the `F0` estimator is unbiased?

![plot-f0-vs-k-kmerstream1 1](https://cloud.githubusercontent.com/assets/291551/16129820/57789c8a-33bb-11e6-9dfb-d8a1b96306e8.png)

**Comment by pmelsted** [comment]
The estimator is not unbiased in the sense that it uses randomness and the expected value is not exactly F0. Rather the epsilon value, default e=0.01 sets the internal parameters so that |F0-x| < e, where x is the estimator, holds with 99% probability.

**Comment by sjackman** [comment]
Thanks for the explanation.
