### ISSUE TITLE
--online option doesn't print anything when --threads used ?

### ISSUE THREAD

**Issue by tseemann** [pmelsted/KmerStream#9]
This gives output

```
KmerStream -k 51 --verbose --online SRR1300467_1.fastq.gz
```

This doesn't

```
KmerStream -k 51 --verbose --online SRR1300467_1.fastq.gz -t 72
```

**Comment by pmelsted** [comment]
Sorry, that's due to poor documentation. I didn't implement the online option for the threaded mode. Also if you are running a single parameter (k or q cutoff) the threads won't help since it doesn't parallelize over reads but parameter configurations.

**Comment by tseemann** [comment]
Ok, so parallel(k) not parallel(fastq).
